services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:java19
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
      - 24454:24454
    volumes:
      - ./data:/data:z
      - ./config:/config:Z,ro
      - ./plugins:/plugins:Z,ro
    env_file:
      - ./minecraft.env
      - ./secrets/minecraft-secrets.env
    cap_add:
      # https://spark.lucko.me/docs/misc/Using-async-profiler#allow-access-to-kernel-perf-events
      - SYS_ADMIN  # allow spark plugin's async-profiler access to perf-events
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file: ./secrets/cloudflare-secrets.env
